
workflows:
  android-workflow:
    name: CI CD TUTORIAL
    instance_type: mac_mini_m1
    max_build_duration: 10
    environment:
      vars:
        PACKAGE_NAME: "com.example.flutter_learn_the_basics" # <-- Put your package name here
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Build APK with Flutter
        script: |
        
          flutter build apk --split-per-abi --release \
            --build-name=1.0.1 \
            --build-number=1
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
        - daniel_hafiz@upm.edu.my
        notify:
          success: true # To not receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fai

